version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:latest
    dependencies:
      pre:
        - npm install angular-cli@latest -g  
    steps:
      - checkout
      - run:
          name: node-env
          command: echo 'export NODE_ENV="production"' >> $BASH_ENV
      - run:
          name: close-env
          command: echo 'export CLOSE="true"' >> $BASH_ENV    
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: api
          command: npm run dev
      - run:
          name: client
          command: sudo npm run build
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results: 
          path: test-results.xml